### ISSUE TITLE
http failure during parsing

### ISSUE THREAD

**Issue by Articunois23** [floogulinc/hydrus-web#116]
Hi, I'm trying to access my Hydrus files on my Android device so I can manage files more conveniently.  I tried following the steps in the wiki but keep getting "verift access key" error. What am I doing wrong?

Let me know what logs to share to help identify the issue.

When I go to my Duck DNS domain, I'm able access the Hydrus API. I'm using the Tailscape IP and have connected both my PC and Android device to it.

**Comment by floogulinc** [comment]
Please ensure you've set the settings for the API in Hydrus as shown in the screenshot in the guide. Especially the CORS setting.

**Comment by floogulinc** [comment]
Can you screenshot what you get when you visit the duckdns domain on your phone and what you're putting in the Hydrus Web API settings? If you would rather not post those here you can send them to me via Discord, email, or any other service I have listed on my website.

**Comment by floogulinc** [comment]
Please post your Caddyfile

**Comment by floogulinc** [comment]
You have to include `https://` in the url you enter in Hydrus Web.

**Comment by floogulinc** [comment]
> When entering the same domain address on my Tablet however, it shows loading for sometime and ends up in a "site can't be reached" error.

This is probably a firewall or other network issue on your local network assuming you're using the correct IP. Part of why I recommend Tailscale is because it avoids issues like that. 

> Also, I had a doubt about the Email address in "Caddyfile". How can it be helpful in obtaining my https certificate? I'm not adding my Email address in Hydrus, Duck DNS... e.t.c. right?

The email address is only used by Let's Encrypt to email you about your certificate expiring or other issues.

**Comment by floogulinc** [comment]
Please format your replies better. This is hard to read because half your reply is in the quote

**Comment by floogulinc** [comment]
You need to give the API key full permissions...

**Comment by floogulinc** [comment]
First make sure your network is set to private in the Windows settings.

Windows should've already asked you to add a firewall rule the first time you enabled the API, it would look like this: 
![rundll32_m6YWIlutBo](https://user-images.githubusercontent.com/1300395/229309857-125b1371-0618-4a17-8e7e-034504d48e66.png)

You may have clicked cancel or closed the window in which case the rules were added but set to block connections. If you open the WIndows Firewall settings you should see a couple rules like this:
![mmc_wdkOOs8Fj4](https://user-images.githubusercontent.com/1300395/229310020-4432ee43-295b-4ec2-938f-61e4a7e584d1.png)


Edit them and set them to "Allow the connection". Otherwise if the rules aren't there you can add them.
