### ISSUE TITLE
Fetch files by ID when tag limited

### ISSUE THREAD

**Issue by blakexiaolong** [floogulinc/hydrus-web#51]
[Per the Hydrus API docs](https://hydrusnetwork.github.io/hydrus/help/client_api.html#get_files_file), if the current API user is tag limited, they need to request files, metadata, and thumbnails by file_id, not file hash.

If a tag limited user is trying to use the web app, and perform a valid search, to which they have rights, they get back a bunch of greyed out thumbnails and a bunch of 403's, and can't access the files when they click on them either.

I see there's an old issue changing from file_id to hash because of caching, but currently tag limited users can't view images at all.

![image](https://user-images.githubusercontent.com/11719967/134573340-3d41c929-39a8-49d7-929f-2f4f5ecd2f75.png)

**Comment by floogulinc** [comment]
Generally Hydrus Web doesn't support being tag limited and expects full access to the hydrus client API, it's expected to be used only by the owner of the hydrus instance and I'd suggest other options for sharing files with others like https://github.com/floogulinc/hyshare and https://github.com/funmaker/Hybooru.

I'm closing this issue now because Hydrus Web has become complex enough that it would be a fair amount of work to use file IDs for everything and it would still run into issues if tag limited.
